### ISSUE TITLE
Hi guys,

### ISSUE THREAD

**Issue by Oleg43414** [proseltd/Telepathy-Community#48]
what to do about it?

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin-PC\AppData\Local\Programs\Python\Python311\Scripts\pip3.exe\__main__.py", line 4, in <module>
  File "C:\Users\Admin-PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\__init__.py", line 4, in <module>
    from pip._internal.utils import _log
  File "C:\Users\Admin-PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\utils\_log.py", line 8, in <module>
    import logging
  File "C:\Users\Admin-PC\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 43, in <module>
    import threading
  File "C:\Users\Admin-PC\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 974
    else:
    ^
IndentationError: expected an indented block after 'try' statement on line 973

**Comment by Oleg43414** [comment]
thank you very much
